version: "2"
services:
    frontend:
        build: ./frontend
        image: frontend
        container_name: frontend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - backend:backend
        networks:
            - webappnetwork
    backend:
        build: ./backend
        image: backend
        container_name: backend
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongo
        networks:
            - webappnetwork
        environment:
            - DATABASE_HOST=mongo
        links:
            - mongo:mongo

    mongo:
        build: ./mongodb
        image: mongo
        restart: always
        container_name: mongo
        volumes:
            - ./data/data:/data/db
        ports:
            - 27017:27017
        command: --auth
        networks:
            - webappnetwork
        environment:
            -MONGO_INITDB_ROOT_USERNAME: admin
            -MONGO_INITDB_ROOT_PASSWORD: 1234
            -MONGO_INITDB_DATABASE: BrydeTech
networks:
    webappnetwork:
        driver: bridge            
            


